apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: plex-ingress
  namespace: plex-media
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
    ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
  - host: plex.tino.sh
    http:
      paths:
      - backend:
          serviceName: plex-media-service
          servicePort: 8080
  tls:
  - hosts:
    - plex.tino.sh
    secretName: plex-tino-sh-tls
