apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: plex-media
  name: plex-pvc-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 60Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: plex-media
  name: plex-pvc-config
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 2Gi
